version: '3.8'

services:
  traefik:
    image: traefik:v2.7
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
    ports:
      - "80:80"      
      - "8080:8080" 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - traefik
  frontend:
    build:
      context: ./dish-dash-frontend
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.priority=1"
    ports:
      - "3000:3000"
    networks:
      - traefik
      

networks:
  traefik:
