version: "3.8"

services:
  go-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-backend
    depends_on:
      - database
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go-backend.rule=PathPrefix(`/api`)"
      - "traefik.http.services.go-backend.loadbalancer.server.port=80"
    networks:
      - proxynet
      - database

  database:
    restart: unless-stopped
    image: postgres:15
    container_name: database
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - ~/.pg/dishdash-db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - database

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    env_file:
      - .env
    ports:
      - "1000:8080"
    depends_on:
      - database
    networks:
      - database

networks:
  proxynet:
    name: proxynet
    external: true
  database: